org: capizahe

plugins:

app: image-service
service: image-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  ImageService:
    handler: handler.handler
    events:
     - http:
         path: /
         method: get
         cors: true
     - http:
         path: /{proxy+}
         method: any
         cors: true 
               